In [1]:
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

## Линейно-взвешенная комбинация

In [7]:
v1 = np.array([[4, 5, 1]]).T
v2 = np.array([[-4, 0, -4]]).T
v3 = np.array([[1, 3, 2]]).T
l1, l2, l3 = 1, 2, -3

w = l1*v1 + l2*v2 + l3*v3
print(w)

[[ -7]
 [ -4]
 [-13]]


## Линейная независимость

In [12]:
v1 = np.array([[1.0, 3.0]])
v2 = np.array([[2.0, 6.0]])
l = 0.5

print(
    f"v1: {v1}\n"
    f"v2: {v2}\n"
    f"v2*l: {v2*l}"
)

v1: [[1. 3.]]
v2: [[2. 6.]]
v2*l: [[1. 3.]]


## Математика линейной независимости

In [2]:
def check_linear(v1, v2, l1, search_limit, step):

    l1 = 1.0  # Фиксируем первый вектор
    search_range = np.arange(-search_limit, search_limit + step, step)

    for l2 in search_range:
        # Вычисляем итоговый вектор: 1.0*v1 + l2*v2
        res_x = l1 * v1[0] + l2 * v2[0]
        res_y = l1 * v1[1] + l2 * v2[1]

        print(f"Если l2 = {l2:4}: то результат = [{res_x:5}, {res_y:5}]", end="")

        if res_x == 0 and res_y == 0:
            print(" <---")
        else:
            print("")

In [5]:
v1 = np.array([1.0, 3.0])
v2 = np.array([2.0, 6.0])
check_linear(v1, v2, l1=1, search_limit=3, step=0.5)

Если l2 = -3.0: то результат = [ -5.0, -15.0]
Если l2 = -2.5: то результат = [ -4.0, -12.0]
Если l2 = -2.0: то результат = [ -3.0,  -9.0]
Если l2 = -1.5: то результат = [ -2.0,  -6.0]
Если l2 = -1.0: то результат = [ -1.0,  -3.0]
Если l2 = -0.5: то результат = [  0.0,   0.0] <---
Если l2 =  0.0: то результат = [  1.0,   3.0]
Если l2 =  0.5: то результат = [  2.0,   6.0]
Если l2 =  1.0: то результат = [  3.0,   9.0]
Если l2 =  1.5: то результат = [  4.0,  12.0]
Если l2 =  2.0: то результат = [  5.0,  15.0]
Если l2 =  2.5: то результат = [  6.0,  18.0]
Если l2 =  3.0: то результат = [  7.0,  21.0]


In [4]:
v1 = np.array([1.0, 3.0])
v2 = np.array([2.0, 7.0])
check_linear(v1, v2, l1=1, search_limit=3, step=0.5)

Если l2 = -3.0: то результат = [ -5.0, -18.0]
Если l2 = -2.5: то результат = [ -4.0, -14.5]
Если l2 = -2.0: то результат = [ -3.0, -11.0]
Если l2 = -1.5: то результат = [ -2.0,  -7.5]
Если l2 = -1.0: то результат = [ -1.0,  -4.0]
Если l2 = -0.5: то результат = [  0.0,  -0.5]
Если l2 =  0.0: то результат = [  1.0,   3.0]
Если l2 =  0.5: то результат = [  2.0,   6.5]
Если l2 =  1.0: то результат = [  3.0,  10.0]
Если l2 =  1.5: то результат = [  4.0,  13.5]
Если l2 =  2.0: то результат = [  5.0,  17.0]
Если l2 =  2.5: то результат = [  6.0,  20.5]
Если l2 =  3.0: то результат = [  7.0,  24.0]


## Независимость и вектор нулей

## Подпространство и охват
- Подпространство - это то место, куда можно попасть, используя только имеющиеся векторы если бесконечное количество раз их модифицировать.

In [ ]:
# Код 3d визуализаций в соседнем блокноте

## Базис

In [14]:
# 1. Исходные данные
p_s = np.array([3, 1])
q_s = np.array([-6, 2])
t1 = np.array([3, 1])
t2 = np.array([-3, 1])

# Координаты в новом базисе T (те самые "красивые" числа)
p_t = np.array([1, 0])
q_t = np.array([0, 2])

# 2. Создаем сабплоты
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=('Старый "набор линеек"', 'Новый "набор линеек"')
)

# --- ГРАФИК 1 (Базис S) ---
# Рисуем стандартную сетку
for i in range(-8, 9, 2):
    fig.add_trace(go.Scatter(x=[-8, 8], y=[i, i], mode='lines', line=dict(color='lightgray', width=1), showlegend=False), 1, 1)
    fig.add_trace(go.Scatter(x=[i, i], y=[-8, 8], mode='lines', line=dict(color='lightgray', width=1), showlegend=False), 1, 1)

# Векторы t1 и t2 как направления в старом мире
fig.add_trace(go.Scatter(x=[0, t1[0]], y=[0, t1[1]], mode='lines+markers',
                         line=dict(color='red', width=3), name="t1 (будущая ось X)"), 1, 1)
fig.add_trace(go.Scatter(x=[0, t2[0]], y=[0, t2[1]], mode='lines+markers',
                         line=dict(color='green', width=3), name="t2 (будущая ось Y)"), 1, 1)

# Точки p и q
fig.add_trace(go.Scatter(x=[p_s[0]], y=[p_s[1]], mode='markers+text', text="p(3,1)",
                         textposition="top right", name="p", marker=dict(size=12, color='red')), 1, 1)
fig.add_trace(go.Scatter(x=[q_s[0]], y=[q_s[1]], mode='markers+text', text="q(-6,2)",
                         textposition="top left", name="q", marker=dict(size=12, color='green')), 1, 1)


# --- ГРАФИК 2 (Базис T) ---
# Рисуем новую сетку (теперь она прямая)
for i in range(-3, 4):
    fig.add_trace(go.Scatter(x=[-3, 3], y=[i, i], mode='lines', line=dict(color='lightgray', width=1), showlegend=False), 1, 2)
    fig.add_trace(go.Scatter(x=[i, i], y=[-3, 3], mode='lines', line=dict(color='lightgray', width=1), showlegend=False), 1, 2)

# ВЫДЕЛЯЕМ НОВЫЕ ОСИ (единичные векторы в новом мире)
fig.add_trace(go.Scatter(x=[0, 1], y=[0, 0], mode='lines+markers',
                         line=dict(color='red', width=4), name="t1 (новая ось X)"), 1, 2)
fig.add_trace(go.Scatter(x=[0, 0], y=[0, 1], mode='lines+markers',
                         line=dict(color='green', width=4), name="t2 (новая ось Y)"), 1, 2)

# Точки в координатах T (теперь они лежат СТРОГО на осях!)
fig.add_trace(go.Scatter(x=[p_t[0]], y=[p_t[1]], mode='markers+text', text="p(1,0)",
                         textposition="top right", marker=dict(size=14, color='red', symbol='x'), showlegend=False), 1, 2)
fig.add_trace(go.Scatter(x=[q_t[0]], y=[q_t[1]], mode='markers+text', text="q(0,2)",
                         textposition="top left", marker=dict(size=14, color='green', symbol='x'), showlegend=False), 1, 2)

# Оформление
fig.update_layout(height=500, width=1000, template="plotly_white", showlegend=True)
fig.update_xaxes(zeroline=True, zerolinewidth=2, zerolinecolor='black', row=1, col=1, range=[-8, 8])
fig.update_yaxes(zeroline=True, zerolinewidth=2, zerolinecolor='black', row=1, col=1, range=[-5, 5])
fig.update_xaxes(zeroline=True, zerolinewidth=2, zerolinecolor='black', row=1, col=2, range=[-3, 3])
fig.update_yaxes(zeroline=True, zerolinewidth=2, zerolinecolor='black', row=1, col=2, range=[-3, 3])

fig.show()

## Задания

### 3.1
Перепишите исходный код линейно-взвешенной комбинации, но поместите скаляры в список, а векторы – в качестве элементов в списке (таким образом,
у вас будет два списка, один из скаляров и один из массивов NumPy). Затем примените цикл for, чтобы реализовать операцию линейно-взвешенной комбинации. Инициализируйте выходной вектор функцией np.zeros(). Подтвердите, что вы получаете тот же результат, что и в приведенном ранее исходном коде

In [13]:
scalars = [1, 2, -3]
vectors = [
    np.array([4,5,1]),
    np.array([-4,0,-4]),
    np.array([1,3,2])
]

res = []
for i in range(len(scalars)):
    res.append(scalars[i] * vectors[i])

sum_res = sum(res)
sum_res


array([ -7,  -4, -13])

### 3.2
Хотя метод прокручивания списков из предыдущего упражнения в цикле не так эффективен, как умножение матриц на векторы, он более масштабируем, чем без цикла for.
Этот факт можно обследовать, добавив в качестве элементов списков дополнительные скаляры и векторы.
 - Что произойдет, если новый добавленный вектор находится в ℝ4, а ℝ3?
- А что произойдет, если у вас будет больше скаляров, чем векторов?

In [30]:
scalars = [1, 2, -3, 5]
vectors = [
    np.array([4,5,1]),
    np.array([-4,0,-4]),
    np.array([1,3,2])
]

In [31]:
# Если через индексы, то упадет
res = []
for i in range(len(scalars)):
    res.append(scalars[i] * vectors[i])

sum_res = sum(res)
sum_res

IndexError: list index out of range

In [33]:
# Если через zip то сработает, так как zip берет минимальную длину из кортежа
res = []
for s,v in zip(scalars,vectors):
  res.append(s*v)
sum(res)

array([ -7,  -4, -13])

## 3.3
В этом упражнении вы будете извлекать случайные точки в подпространствах. Благодаря этому упражнению вы укрепите идею о том, что подпространства содержат любую линейно-взвешенную комбинацию охватывающих векторов.

- Определите множество векторов, содержащее один вектор [1,3].
- Затем
    - создайте 100 чисел, выбранных случайным образом из равномерного распределения между –4 и +4. Это ваши случайные скаляры.
    - умножьте случайные скаляры на базисный вектор, чтобы создать 100 случайных точек в подпространстве.
    - нанесите эти точки на 2д и 3д график.
- Затем
    - повторите процедуру, но используя два вектора в ℝ3: [3, 5, 1] и [0, 2, 2]. Обратите внимание, что для 100 точек и двух векторов вам нужно 100×2 случайных скаляров.
    - нанесите эти точки на 2д и 3д график

In [56]:
A = np.array([1,3])
scalars = np.random.uniform(-4, 4, 100)

points = np.array([s * A for s in scalars])

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=points[:, 0],
    y=points[:, 1],
    mode='markers')
)

fig.update_layout(
    title="Точки на плоскости",
    xaxis=dict(title='X', zeroline=True, range=[-5, 5]),
    yaxis=dict(title='Y', zeroline=True, range=[-15, 15]),
    width=600, height=600
)

fig.show()

In [7]:
# 1. Определяем наши векторы
v1 = np.array([3, 5, 1])
v2 = np.array([0, 2, 2])

# 2. Генерируем случайные скаляры для создания облака точек
n_points = 1000
scalars_1 = np.random.uniform(-1, 1, n_points)
scalars_2 = np.random.uniform(-1, 1, n_points)

# Вычисляем точки: P = s1*v1 + s2*v2
span_points = np.array([s1 * v1 + s2 * v2 for s1, s2 in zip(scalars_1, scalars_2)])

fig = go.Figure()

# Добавляем облако точек (подпространство)
fig.add_trace(go.Scatter3d(
    x=span_points[:, 0],
    y=span_points[:, 1],
    z=span_points[:, 2],
    mode='markers',
    marker=dict(size=3, color='lightblue', opacity=0.5),
    name='Точки подпространства (Span)'
))

# Добавляем вектор v1
fig.add_trace(go.Scatter3d(
    x=[0, v1[0]], y=[0, v1[1]], z=[0, v1[2]],
    mode='lines+markers',
    line=dict(color='red', width=6),
    marker=dict(size=5),
    name='Вектор v1 [3, 5, 1]'
))

# Добавляем вектор v2
fig.add_trace(go.Scatter3d(
    x=[0, v2[0]], y=[0, v2[1]], z=[0, v2[2]],
    mode='lines+markers',
    line=dict(color='green', width=6),
    marker=dict(size=5),
    name='Вектор v2 [0, 2, 2]'
))

fig.update_layout(
    title="Подпространство двух векторов в 3D",
    scene=dict(
        xaxis_title='X',
        yaxis_title='Y',
        zaxis_title='Z',
        camera=dict(eye=dict(x=1.5, y=1.5, z=1.2))
    ),
    margin=dict(l=0, r=0, b=0, t=40),
)

fig.show()