In [1]:
import numpy as np

# Глава

## Создание и визуализация матриц в NumPy

In [22]:
rows = 4
cols = 6
A = np.random.rand(4,6)
print(A)

[[0.73266925 0.34049356 0.90373956 0.51097817 0.40457003 0.36398237]
 [0.97451612 0.55442637 0.58976789 0.14386007 0.42507202 0.6098751 ]
 [0.39288559 0.54431084 0.17225485 0.40949799 0.3088804  0.09470778]
 [0.16129768 0.02849397 0.07144242 0.41933012 0.91990842 0.92382112]]


In [32]:
A = np.diag([1, 2, 4, 16])
b = np.diag(A)

print(A, b, sep="\n\n")

[[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  4  0]
 [ 0  0  0 16]]

[ 1  2  4 16]


In [53]:
A = np.arange(1, 17).reshape(4, 4)
A1 = np.tril(A, 0)
A2 = np.triu(A, 0)
print(A, A1, A2, sep="\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]
 [13 14 15 16]]

[[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]]


In [71]:
A = np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [70]:
A = np.zeros((4,4))
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


f## Матричная математика: сложение, умножение на скаляр, адамарово умножение

## Стандартное умножение матриц

## Матричные операции. Транспанирование

## Матричные операции. LIVE EVIL

## Симметричные матрицы

# Задания

## Упражнение 5.1
- Создайте матрицу 3×4, используя np.arange(12).reshape(3,4).
- Затем напишите исходный код на Python, чтобы извлечь элемент во второйстроке, четвертом столбце. Используйте мягкое программирование, чтобы
выбирать разные индексы строк/столбцов.
- Найдите элемент по индексу (1,3)

In [25]:
matrix = np.arange(12).reshape(3, 4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
target = (1, 3)
print(matrix[target[0]][target[1]])

7


## Упражнение 5.2
- Создайте матрицу 10х10 с числами от 0 до 99
- Примените существующую в Python операцию нарезки, чтобы извлечь подматрицу, состоящую из первых пяти строк и пяти столбцов.

In [29]:
matrix = np.arange(100).reshape(10, 10)
print(matrix)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [33]:
print(matrix[0:5, 0:5])

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


## Упражнение 5.3
- Создайте матрицу 10х10 с числами от 0 до 99
- Сделайте нарезку матрицы на блоки размером 5х5
- Сделайте новую матрицу из нарезанных блоков так, чтобы они поменялись местами отностиельно изначальной матрицы.

In [41]:
matrix = np.arange(100).reshape(10, 10)
print(matrix)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [53]:
block_1 = matrix[0:5, 0:5]
block_2 = matrix[0:5, 5:]
block_3 = matrix[5:, 0:5]
block_4 = matrix[5:, 5:]

sector_1 = np.concat((block_4, block_3), axis=1)
sector_2 = np.concat((block_2, block_1), axis=1)
result = np.concat((sector_1, sector_2), axis=0)
print(result)

[[55 56 57 58 59 50 51 52 53 54]
 [65 66 67 68 69 60 61 62 63 64]
 [75 76 77 78 79 70 71 72 73 74]
 [85 86 87 88 89 80 81 82 83 84]
 [95 96 97 98 99 90 91 92 93 94]
 [ 5  6  7  8  9  0  1  2  3  4]
 [15 16 17 18 19 10 11 12 13 14]
 [25 26 27 28 29 20 21 22 23 24]
 [35 36 37 38 39 30 31 32 33 34]
 [45 46 47 48 49 40 41 42 43 44]]


## Упражнение 5.4
- Реализуйте поэлементное сложение матриц, используя два цикла for по строкам и столбцам.
- Что происходит, когда вы пытаетесь сложить две матрицы с несовпадающими размерами?
- Это упражнение поможет вам подумать о разбиении матрицы на строки, столбцы и отдельные элементы.

In [26]:
matrix_1 = np.arange(12).reshape(3, 4)
matrix_2 = np.arange(12).reshape(3, 4)
matrix_3 = np.arange(6).reshape(3, 2)
print(matrix_1, matrix_2, matrix_3, sep="\n\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[0 1]
 [2 3]
 [4 5]]


In [106]:
def matrix_plus_matrix(matrix_1, matrix_2):
    result = np.zeros_like(matrix_1)

    for i in range(matrix_1.shape[0]):
        for j in range(matrix_1.shape[1]):
            result[i, j] = matrix_1[i, j] + matrix_2[i, j]
    print(result)

In [107]:
matrix_plus_matrix(matrix_1, matrix_2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [108]:
matrix_plus_matrix(matrix_1, matrix_3)

IndexError: index 2 is out of bounds for axis 1 with size 2

## Упражнение 5.5
Допустим, что матрицы A и B имеют одинаковый размер и что σ является неким скаляром: $$\large \sigma(A+B)=\sigma A + \sigma B = A \sigma + B \sigma$$

- Создайте две матрицы случайных чисел размером 3×4 и случайный скаляр.
- Затем реализуйте три выражения в приведенном выше уравнении.
- Вам нужно будет найти способ подтвердить эквивалентность трех результатов. Имейте в виду,
что крошечные ошибки вычислительной прецизионности в диапазоне $10^-15$ следует игнорировать

In [62]:
A = np.random.rand(12).reshape(3, 4)
B = np.random.rand(12).reshape(3, 4)
s = np.random.rand()

np.allclose(s * (A + B), s * A + s * B, rtol=0, atol=1e-15)

True

## Упражнение 5.6
Запрограммируйте умножение матриц с использованием циклов for. Подтвердите свои результаты с помощью оператора @ библиотеки NumPy. Это упражнение поможет вам укрепить ваше понимание умножения матриц, но на практике всегда лучше использовать @ вместо написания двойного цикла for.

In [22]:
A = np.arange(1, 10).reshape(3, 3)
B = np.arange(11, 20).reshape(3, 3)
print(A, B, sep="\n\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [23]:
def multiply_matrix(matrix_a, matrix_b):
    # Проверить, что М-строк matrix_1 == K-столбцов matrix_2
    a_row, a_col = matrix_a.shape[0], matrix_a.shape[1]
    b_row, b_col = matrix_b.shape[0], matrix_b.shape[1]

    if a_row != b_col:
        print(f"Нельзя умножить. Размерности матриц не совпадают. {matrix_a.shape} и {matrix_b.shape}")

    # Заготовка для результата
    result = np.zeros_like(matrix_a)

    # Перебираем строки/столбцы
    for i in range(a_row):
        row = matrix_a[i:i + 1, :][0]
        # print(row)

        for j in range(b_col):
            col = matrix_b[:, j]
            # print(col)

            value = np.sum([row[_] * col[_] for _ in range(len(row))])
            # result.append(value)

            result[i][j] = value

    return result

In [25]:
print(multiply_matrix(A, B))

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [158]:
print(A @ B)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [159]:
print(np.dot(A, B))

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


## Упражнение 5.7
Подтвердите правило LIVE EVIL, выполнив следующие пять шагов.
1. Создайте четыре матрицы случайных чисел, установив размеры $A \in \mathbb{R}^{2\ast6}, B \in \mathbb{R}^{6\ast3}, C \in \mathbb{R}^{3\ast5}, D \in \mathbb{R}^{5\ast2}$.
2. Умножьте четыре матрицы и транспонируйте произведение.
3. Транспонируйте каждую матрицу по отдельности и умножьте их, не меняя их порядок следования.
4. Транспонируйте каждую матрицу по отдельности и умножьте их в обратном порядке в соответствии с правилом LIVE EVIL. Проверьте совпадение результата шага 2 с результатами шага 3 и шага 4.
5. Повторите приведенные выше шаги, но используя только квадратные матрицы.

In [45]:
# Шаг 1
slice = (0, 100)
L = np.random.randint(*slice, size=12).reshape(2, 6)
I = np.random.randint(*slice, size=18).reshape(6, 3)
V = np.random.randint(*slice, size=15).reshape(3, 5)
E = np.random.randint(*slice, size=10).reshape(5, 2)

In [51]:
# Шаг 2
res_1 = (L @ I @ V @ E).T
# res_2 = (L.T @ I.T @ V.T @ E.T) # нарушает условие умножения матриц, ошибка
res_3 = (E.T @ V.T @ I.T @ L.T)

In [59]:
is_equal = np.array_equal(res_1, res_3)
print(f"is_equal:{is_equal}", res_1, res_3, sep="\n\n")

is_equal:True

[[486237554 328958458]
 [578403252 388412546]]

[[486237554 328958458]
 [578403252 388412546]]


## Упражнение 5.8
В этом упражнении вы напишете функцию Python, которая выполняет проверку матри цы на симметричность. На входе она должна принимать матрицу и на выходе выводить булево значение True, если матри ца является симметричной, либо False, если матрица является несимметричной.
Имейте в виду, что малые ошибки вычислительного округления/прецизионности могут создавать впечатление, что «равные» матрицы являются неравными. Следовательно, вам нужно будет выполнять проверку на равенство с некоторой разумной терпимостью. Протестируйте функцию на симметричных
и несимметричных матрицах.

In [91]:
A = np.array([3 for _ in np.arange(9)]).reshape(3, 3)
B = np.random.randint(0, 100, 9).reshape(3, 3)

In [89]:
def is_symmetric_matrix(matrix):
    result = False

    if np.array_equal(matrix, matrix.T):
        result = True

    return result

In [93]:
is_symmetric_matrix(A)

True

In [94]:
is_symmetric_matrix(B)

False

## Упражнение 5.9
Я упоминал, что существует аддитивный метод создания симметричной матрицы из несимметричной квадратной матрицы. Указанный метод довольно прост: усреднить матрицу посредством ее транспонированной версии. Реализуйте этот алгоритм на Python и подтвердите, что результат
действительно является симметричным. (Подсказка: используйте функцию,
которую вы написали в предыдущем упражнении!)

In [102]:
A = np.random.randint(0, 9, 9).reshape(3, 3)
print(A)
is_symmetric_matrix(A)

[[5 0 2]
 [7 2 0]
 [1 7 5]]


False

In [103]:
As = A.T @ A
print(As)
is_symmetric_matrix(As)

[[75 21 15]
 [21 53 35]
 [15 35 29]]


True

### Упражнение 5.11
Диагональные матрицы обладают многими интересными свойствами, которые делают их полезными для работы. В данном упражнении вы узнаете о двух из этих свойств:
- предпозиционное умножение диагональной матрицы на матрицу-сомножитель шкалирует строки правой матрицы на соответствующие диагональные элементы;
- постпозиционное умножение диагональной матрицы на матрицу-сомножитель шкалирует столбцы левой матрицы на соответствующие диагональные элементы.

Этот факт используется в нескольких приложениях, включая вычисление матриц корреляций (глава 7) и диагонализацию матриц (главы 13 и 14). Давайте обследуем последствия этих свойств. Начнем с создания трех матриц 4×4:
- матрицы из одних единиц (подсказка: np.ones());
- диагональной матрицы, в которой диагональные элементы равны 1, 4, 9 и 16;
- диагональной матрицы, равной квадратному корню из предыдущей диагональной матрицы.

Далее распечатайте матрицу единиц, пред- и постпозиционно умноженную на первую диагональную матрицу-сомножитель. Вы получите следующие ниже результаты

```
# Предпозиционно умножить на диагональную матрицу:
[[ 1. 1. 1. 1.]
[ 4. 4. 4. 4.]
[ 9. 9. 9. 9.]
[16. 16. 16. 16.]]

# Постпозиционно умножить на диагональную матрицу:
[[ 1. 4. 9. 16.]
[ 1. 4. 9. 16.]
[ 1. 4. 9. 16.]
[ 1. 4. 9. 16.]]
```

Наконец, предпозиционно и постпозиционно умножьте матрицу единиц на матрицу квадратных корней из диагональной матрицы. Вы получите следующее ниже:
```
# Пред- и постпозиционно умножить на квадратично-диагональную матрицу
[[ 1. 2. 3. 4.]
[ 2. 4. 6. 8.]
[ 3. 6. 9. 12.]
[ 4. 8. 12. 16.]]
```
Обратите внимание, что строки и столбцы прошкалированы таким образом, что (i, j)-й элемент в матрице умножается на произведение i-го и j-го диагональных элементов. (На самом деле мы создали таблицу умножения!).

In [10]:
A = np.ones(16).reshape(4,4)
B = np.diag([1,4,9,16])
C = np.diag([np.sqrt(_) for _ in [1,4,9,16]])

In [13]:
# Предпозиционно умножить на диагональную матрицу:
print(B@A)

[[ 1.  1.  1.  1.]
 [ 4.  4.  4.  4.]
 [ 9.  9.  9.  9.]
 [16. 16. 16. 16.]]


In [14]:
# Постпозиционно умножить на диагональную матрицу:
print(A@B)

[[ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]]


In [20]:
# Пред- и постпозиционно умножить на квадратично-диагональную матрицу
print(C@A@C)

[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]
 [ 3.  6.  9. 12.]
 [ 4.  8. 12. 16.]]


Это отличный вопрос. Чтобы понять «магию» диагональных матриц, нужно на секунду забыть о громоздких формулах и посмотреть, как работает обычное умножение матрицы на вектор.Диагональная матрица — это по сути набор индивидуальных коэффициентов. Она не перемешивает данные (как обычные матрицы), а просто говорит каждому элементу: «Стань во столько-то раз больше».
1. Почему «слева» — это строки? ($D \cdot A$)Вспомни, как работает умножение матриц «строка на столбец». Когда диагональная матрица $D$ стоит слева:Чтобы получить первую строку результата, мы берем первое число из $D$ и умножаем его на всю первую строку матрицы $A$.Чтобы получить вторую строку — берем второе число из $D$ и умножаем его на всю вторую строку $A$.Простая интуиция: Матрица слева — это «фильтр» на входе. Она перехватывает каждую строку $A$ целиком и масштабирует её своим коэффициентом.
2. Почему «справа» — это столбцы? ($A \cdot D$)Теперь поменяем их местами. Когда $D$ стоит справа:По правилу умножения, первый столбец результата — это линейная комбинация столбцов $A$. Но так как в $D$ в первом столбце есть только одно число на первой позиции, оно «вытягивает» из $A$ только первый столбец и умножает его на себя.Второй элемент на диагонали $D$ «занимается» только вторым столбцом $A$.Простая интуиция: Матрица справа — это «настройка» выходов. Она берет готовые столбцы $A$ и подправляет их масштаб.
3. Магия «Сэндвича» ($D \cdot A \cdot D$)Когда мы делаем $D \cdot A \cdot D$, происходит двойная фильтрация. Представь таблицу умножения.Элемент на пересечении $i$-й строки и $j$-го столбца в матрице $A$ (допустим, там была единица):Сначала умножается на $i$-й элемент левой матрицы (масштаб строки).А потом умножается на $j$-й элемент правой матрицы (масштаб столбца).В итоге каждый элемент $a_{i,j}$ превращается в $a_{i,j} \cdot d_i \cdot d_j$.
4. Почему это критично для Data Science?В Главе 7 ты встретишь это в контексте матрицы корреляций.У тебя есть матрица ковариации $C$, где числа — это огромные значения (например, разброс цен на квартиры в миллионах).Тебе нужно превратить их в корреляции (от -1 до 1).Ты создаешь диагональную матрицу $D$, где на диагонали стоят $1/\sigma$ (обратные стандартные отклонения).Ты делаешь «сэндвич» $D \cdot C \cdot D$.Левая $D$ нормирует строки.Правая $D$ нормирует столбцы.Результат: идеальная матрица корреляций, где на диагонали единицы, а вокруг — значения от -1 до 1.Резюме:Слева — управляем горизонталями (строками).Справа — управляем вертикалями (столбцами).С двух сторон — масштабируем каждое пересечение индивидуально.

### Упражнение 5.12
Еще один забавный факт: умножение матриц – это то же самое, что и адамарово умножение двух диагональных матриц. Подумайте, почему так, используя бумагу и карандаш с двумя диагональными матрицами 3×3, а затем проиллюстрируйте это в исходном коде на Python.